language: python
dist: xenial
python:
  - '2.7'
before_install:
  - pip install -r requirements.txt
  - pip install setuptools
  - sudo apt-get install -y git curl squashfs-tools sed debmake debhelper python-all python3-all python-setuptools python3-setuptools fakeroot python-debian python3-debian
  - mkdir -p ./build
script:
  # Debian
  - python setup.py sdist
  - cd dist
  - tar xvfz tuxemon*.tar.gz
  - cd tuxemon*
  - debmake -b':py2'
  - dpkg-buildpackage -us -uc
  - cd ../..
  - mv ./dist/tuxemon*.deb ./build/tuxemon-unstable-latest.deb
  # GCW-Zero
  - sed -i 's/resolution_x.*/resolution_x = 320/g' tuxemon/tuxemon.cfg
  - sed -i 's/resolution_y.*/resolution_y = 240/g' tuxemon/tuxemon.cfg
  - sed -i 's/fullscreen.*/fullscreen = 1/g' tuxemon/tuxemon.cfg
  - cp tuxemon/resources/gfx/icon_32.png tuxemon/resources/gfx/icon.png
  - mksquashfs tuxemon ./build/tuxemon-unstable-latest.opk -all-root -noappend -no-exports -no-xattrs
branches:
  only:
    - /^travis.*/
